namespace Server
{
    partial class MagicInfoForm
    {
        private System.Windows.Forms.ListBox MagiclistBox;
        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.Label lblBookValid;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox txtSkillIcon;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.TextBox txtSkillLvl3Points;
        private System.Windows.Forms.TextBox txtSkillLvl2Points;
        private System.Windows.Forms.TextBox txtSkillLvl1Points;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.TextBox txtSkillLvl3Req;
        private System.Windows.Forms.TextBox txtSkillLvl2Req;
        private System.Windows.Forms.TextBox txtSkillLvl1Req;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.TextBox txtMPIncrease;
        private System.Windows.Forms.TextBox txtMPBase;
        private System.Windows.Forms.ToolTip toolTip1;
        private System.ComponentModel.IContainer components;
        private System.Windows.Forms.Panel panel3;
        private System.Windows.Forms.TextBox txtDelayReduction;
        private System.Windows.Forms.TextBox txtDelayBase;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Panel panel4;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.Label lblDamageExample;
        private System.Windows.Forms.TextBox txtDmgBonusMax;
        private System.Windows.Forms.TextBox txtDmgBonusMin;
        private System.Windows.Forms.Label label18;
        private System.Windows.Forms.Label label19;
        private System.Windows.Forms.TextBox txtDmgBaseMax;
        private System.Windows.Forms.TextBox txtDmgBaseMin;
        private System.Windows.Forms.Label label17;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.Label lblSelected;
        private System.Windows.Forms.Label label20;
        private System.Windows.Forms.TextBox txtRange;
        private System.Windows.Forms.Label lblDamageExplained;
        private System.Windows.Forms.TextBox txtDmgMultBoost;
        private System.Windows.Forms.TextBox txtDmgMultBase;
        private System.Windows.Forms.Label label21;
        private System.Windows.Forms.Label label22;
    }
}