using System;
using System.IO;
using System.Linq;
using System.Windows.Forms;

namespace Server.Network
{
    public partial class BlockListForm : Form
    {
        public BlockListForm()
        {
            InitializeComponent();

            // Hotkeys and events not generated by designer
            tbList.KeyDown += (s, e) =>
            {
                if (e.Control && e.KeyCode == Keys.A)
                {
                    for (int i = 0; i < tbList.Items.Count; i++) tbList.SetSelected(i, true);
                    e.SuppressKeyPress = true;
                    return;
                }
                if (e.KeyCode == Keys.Delete)
                {
                    DoRemove();
                    e.SuppressKeyPress = true;
                    return;
                }
            };

            Load += (_, __) => RefreshList();
            btnAdd.Click += (_, __) => DoAdd();
            btnRemove.Click += (_, __) => DoRemove();
            btnImport.Click += (_, __) => DoImport();
            btnExport.Click += (_, __) => DoExport();
            btnClose.Click += (_, __) => Close();
        }

        private void RefreshList()
        {
            tbList.BeginUpdate();
            tbList.Items.Clear();
            foreach (var s in Settings.IPBlockListRaw)
                tbList.Items.Add(s);
            tbList.EndUpdate();
        }

        private void DoAdd()
        {
            var line = (tbIPCIDRinput.Text ?? string.Empty).Trim();
            if (string.IsNullOrWhiteSpace(line)) return;
            int added = Settings.ImportIpBlocks(new[] { line });
            if (added > 0)
            {
                Persist();
                RefreshList();
                tbIPCIDRinput.Clear();
            }
            else
            {
                MessageBox.Show(this, "Invalid IP/CIDR or already exists.", "Add", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }

        private void DoRemove()
        {
            var items = tbList.SelectedItems.Cast<object>().Select(x => x?.ToString()).Where(s => !string.IsNullOrEmpty(s)).ToList();
            if (items.Count == 0) return;
            foreach (var s in items)
                Settings.IPBlockListRaw.Remove(s);
            Settings.RebuildIpBlockListFromRaw();
            Persist();
            RefreshList();
        }

        private void DoImport()
        {
            using var ofd = new OpenFileDialog
            {
                Filter = "Text files (*.txt)|*.txt|All files (*.*)|*.*",
                InitialDirectory = Path.GetFullPath("."),
                FileName = "IpBlockList.txt"
            };
            if (ofd.ShowDialog(this) != DialogResult.OK) return;
            try
            {
                var lines = File.ReadAllLines(ofd.FileName);
                int added = Settings.ImportIpBlocks(lines);
                Persist();
                RefreshList();
                MessageBox.Show(this, $"Imported {added} entries.", "Import", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex)
            {
                MessageBox.Show(this, ex.Message, "Import", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void DoExport()
        {
            using var sfd = new SaveFileDialog
            {
                Filter = "Text files (*.txt)|*.txt|All files (*.*)|*.*",
                InitialDirectory = Path.GetFullPath("."),
                FileName = "IpBlockList.txt"
            };
            if (sfd.ShowDialog(this) != DialogResult.OK) return;
            try
            {
                File.WriteAllLines(sfd.FileName, Settings.IPBlockListRaw);
                MessageBox.Show(this, "Export complete.", "Export", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex)
            {
                MessageBox.Show(this, ex.Message, "Export", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void Persist()
        {
            try
            {
                Directory.CreateDirectory(Settings.ConfigPath);
                File.WriteAllLines(Settings.IPBlockListPath, Settings.IPBlockListRaw);
            }
            catch { }
        }
    }
}

